# Connect to Microsoft Graph
Connect-Graph -Scopes User.ReadWrite.All, Organization.Read.All

# Get the SKU for the desired license
$EmsSku = Get-MgSubscribedSku -All | Where-Object { $_.SkuPartNumber -eq 'SPE_E3' }

# Array of User IDs to be processed
$userIds = @(
    'adal@brandcollective.com.au',
    'allenc@brandcollective.com.au',
    'amandah@brandcollective.com.au',
    'AmyG@brandcollective.com.au',
    'amyh@brandcollective.com.au',
    'angelal@brandcollective.com.au',
    'angelas@brandcollective.com.au',
    'anitaz@brandcollective.com.au',
    'Annicad@brandcollective.com.au',
    'Ann-MarieL@brandcollective.com.au',
    'benc@brandcollective.com.au',
    'BrookeN@brandcollective.com.au',
    'caseyp@brandcollective.com.au',
    'chantellec@brandcollective.com.au',
    'chelseab@brandcollective.com.au',
    'ChloeC@brandcollective.com.au',
    'cindyx@brandcollective.com.au',
    'claudial@brandcollective.com.au',
    'colec@brandcollective.com.au',
    'ConnieS@brandcollective.com.au',
    'daisyn@brandcollective.com.au',
    'danielc@brandcollective.com.au',
    'DannyB@brandcollective.com.au',
    'DarrenK@brandcollective.com.au',
    'davidd@brandcollective.com.au',
    'dwaccountspayable@brandcollective.com.au',
    'dwaccountsreceivable@brandcollective.com.au',
    'Dianal@brandcollective.com.au',
    'diannes@brandcollective.com.au',
    'diemv@brandcollective.com.au',
    'elisaf@brandcollective.com.au',
    'elissas@brandcollective.com.au',
    'elizabethv@brandcollective.com.au',
    'elysiat@brandcollective.com.au',
    'emanuelap@brandcollective.com.au',
    'emilye@brandcollective.com.au',
    'emman@brandcollective.com.au',
    'ericz@brandcollective.com.au',
    'erink@brandcollective.com.au',
    'fionam@brandcollective.com.au',
    'Frans@brandcollective.com.au',
    'francesd@brandcollective.com.au',
    'gavinc@brandcollective.com.au',
    'georgiev@brandcollective.com.au',
    'gloriax@brandcollective.com.au',
    'heathd@brandcollective.com.au',
    'helenn@brandcollective.com.au',
    'hollys@brandcollective.com.au',
    'Ilab@brandcollective.com.au',
    'jacquic@brandcollective.com.au',
    'janine@brandcollective.com.au',
    'jessicas@brandcollective.com.au',
    'jimmyc@brandcollective.com.au',
    'joannar@brandcollective.com.au',
    'JodieS@brandcollective.com.au',
    'johns@brandcollective.com.au',
    'julieh@brandcollective.com.au',
    'katherineb@brandcollective.com.au',
    'KevinM@brandcollective.com.au',
    'kikis@brandcollective.com.au',
    'kirstena@brandcollective.com.au',
    'laura-janec@brandcollective.com.au',
    'laureno@brandcollective.com.au',
    'leeh@brandcollective.com.au',
    'leighw@brandcollective.com.au',
    'leoh@brandcollective.com.au',
    'leow@brandcollective.com.au',
    'liamm@brandcollective.com.au',
    'lianh@brandcollective.com.au',
    'lindag@brandcollective.com.au',
    'lindaj@brandcollective.com.au',
    'lizc@brandcollective.com.au',
    'lynnl@brandcollective.com.au',
    'madeleinef@brandcollective.com.au',
    'madelinek@brandcollective.com.au',
    'MarioD@brandcollective.com.au',
    'Matts@brandcollective.com.au',
    'meaganw@brandcollective.com.au',
    'meeganm@brandcollective.com.au',
    'melissas@brandcollective.com.au',
    'melissasm@brandcollective.com.au',
    'mingh@brandcollective.com.au',
    'miriamk@brandcollective.com.au',
    'monicaz@brandcollective.com.au',
    'NancyC@brandcollective.com.au',
    'nataliaj@brandcollective.com.au',
    'natalieb@brandcollective.com.au',
    'natalies@brandcollective.com.au',
    'ngocv@brandcollective.com.au',
    'nicolepo@brandcollective.com.au',
    'peterp@brandcollective.com.au',
    'phoebec@brandcollective.com.au',
    'ppsrdwi@brandcollective.com.au',
    'rachaelb@brandcollective.com.au',
    'rachaelo@brandcollective.com.au',
    'raffaellam@brandcollective.com.au',
    'ritax@brandcollective.com.au',
    'roseb@brandcollective.com.au',
    'roses@brandcollective.com.au',
    'rubyc@brandcollective.com.au',
    'sallyd@brandcollective.com.au',
    'sanikac@brandcollective.com.au',
    'saras@brandcollective.com.au',
    'sarahwi@brandcollective.com.au',
    'siennab@brandcollective.com.au',
    'sivl@brandcollective.com.au',
    'sophieh@brandcollective.com.au',
    'sophiew@brandcollective.com.au',
    'Stephens@brandcollective.com.au',
    'SunnyMa@brandcollective.com.au',
    'taliat@brandcollective.com.au',
    'tiak@brandcollective.com.au',
    'TimL@brandcollective.com.au',
    'traceye@brandcollective.com.au',
    'VanessaT@brandcollective.com.au',
    'veral@brandcollective.com.au',
    'vickyf@brandcollective.com.au',
    'yuccak@brandcollective.com.au'
)

# Iterate through each user ID and set the usage location and license
foreach ($userId in $userIds) {
    # Set the user's usage location to Australia
    Update-MgUser -UserId $userId -UsageLocation "AU"
    
    # Assign the license
    Set-MgUserLicense -UserId $userId -AddLicenses @{SkuId = $EmsSku.SkuId} -RemoveLicenses @()
}
